### ISSUE TITLE
State class for tariff standing & rate sensors are not set

### ISSUE THREAD

**Issue by markcocker** [HandyHat/ha-hildebrandglow-dcc#288]
**Describe the bug**

HA statistics page reports that the state class of the following entities are not supported:

- DCC Sourced smart electricity meter Standing charge (sensor.electric_tariff_standing)
- DCC Sourced smart electricity meter Rate (sensor.electric_tariff_rate)
- DCC Sourced smart gas meter Standing charge (sensor.gas_tariff_standing)
- DCC Sourced smart gas meter Rate (sensor.gas_tariff_rate)

**To Reproduce**

1. Go to Developer Tools > Statistics /developer-tools/statistics
2. See error.

**Expected behaviour**
HA to report no issues.

**Screenshots**
<img width="1309" alt="Screenshot 2023-01-03 at 12 32 53" src="https://user-images.githubusercontent.com/15351000/210359003-ebbe6ac9-10c3-45c3-9eec-d90e57052cad.png">

**Version**
1.0.2

**Comment by HandyHat** [comment]
Hey @markcocker, does this cause any problems elsewhere?
The reason this issue is being reported is that these sensors used to have a state class of measurement and thus have long-term statistics calculated for them. However, looking at the docs (https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes), I don't think they should have done as they aren't a measurement of anything, so I removed the state class.

It should be safe to remove the long term statistics by clicking fix issue, remove.

**Comment by markcocker** [comment]
Thanks for the update.
I have clicked "fix issue" on each of the sensors, restarted, and not seen any other problems.
